trigger:
  branches:
    include:
      - master
      - develop

pr:
  - master
  - develop

pool:
  vmImage: ubuntu-latest

name: SUPERSET_$(Date:yyyyMMdd)$(Rev:.r)

variables:
  # This is the base docker image to use
  # See https://hub.docker.com/r/apache/superset/tags
  SUPERSET_VERSION: "3.0.1"

steps:
  - script: |
      VERSION_TAG=`git describe --abbrev=0 --tags`
      echo "##vso[task.setvariable variable=VERSION_TAG]$VERSION_TAG"

      IMAGE_TAGS="${VERSION_TAG}_$(Build.SourceVersion)"
      echo "##vso[task.setvariable variable=IMAGE_SEMANTIC_HASH]$(SUPERSET_VERSION)-$IMAGE_TAGS"
      if [[ "$(Build.SourceBranch)" == "refs/heads/master" ]]; then IMAGE_TAGS="$IMAGE_TAGS,latest"; fi;
      echo Tags: $IMAGE_TAGS
      echo "##vso[task.setvariable variable=IMAGE_TAGS]$IMAGE_TAGS"
    displayName: Get git tag

  - task: Docker@2
    displayName: Login to Azure registry
    inputs:
      containerRegistry: azurecr-oaf
      command: "login"

  # build and push image
  - task: Docker@2
    displayName: Build oneacrefund/superset
    inputs:
      containerRegistry: azurecr-oaf
      repository: oneacrefund/superset
      command: build
      tags: "$(IMAGE_SEMANTIC_HASH)"
      arguments: --build-arg SUPERSET_VERSION=$(SUPERSET_VERSION)

  - script: |
      docker run --rm oaftech.azurecr.io/oneacrefund/superset:$(IMAGE_SEMANTIC_HASH) python -m unittest discover -s /opt/oaf-tests
    displayName: Test Chrome - Chromedriver integration

  - script: |
      # Patch values file with latest tag
      yq e '.image.tag  = "$(IMAGE_SEMANTIC_HASH)"' values/oaf-values.yaml -i
    displayName: Use latest image tag

  - task: HelmInstaller@1
    inputs:
      helmVersionToInstall: latest

  # - script: |
  #     echo Downloading chart
  #     git submodule init
  #     git submodule update

  #     # See https://kind.sigs.k8s.io/docs/user/quick-start/ for kind usage
  #     # Create cluster 'kind'
  #     kind create cluster --wait 5m
  #     # Side-load image to speed up pull
  #     kind load docker-image oaftech.azurecr.io/oneacrefund/superset:$(IMAGE_SEMANTIC_HASH)

  #     # Install Helm dependencies
  #     helm dependency update superset/helm/superset

  #     kubectl config use-context kind-kind
  #     helm install -f oaf-values.yaml superset superset/helm/superset --wait --timeout 5m
  #     kubectl get pods
  #   displayName: Test deployment

  # Package our values
  - task: CopyFiles@2
    inputs:
      SourceFolder: "$(Build.SourcesDirectory)/releases/values"
      targetFolder: "$(build.artifactStagingDirectory)"

  # build and push image
  - task: Docker@2
    displayName: Publish oneacrefund/superset
    # Only publish develop branch
    # condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    inputs:
      containerRegistry: azurecr-oaf
      repository: oneacrefund/superset
      command: push
      tags: "$(IMAGE_SEMANTIC_HASH)"

  - task: PublishBuildArtifacts@1
    displayName: Publish Helm chart
    # Only publish develop branch
    # condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    inputs:
      PathtoPublish: "$(Build.ArtifactStagingDirectory)"
      ArtifactName: "superset"
      publishLocation: "Container"
