name: Dispatch external pipeline
description: Dispatch deployment workflow.
inputs:
  GA_TOKEN:
    description: The token with repo access
  RUN_ID:
    description: The unique run ID of the triggering workflow
    required: true
  REF:
    description: The triggering workflow source branch
    required: true
  DISPATCH_REPO:
    description: The name of the repo to dispatch.
    required: true
runs:
  using: composite
  steps:
    name: Dispatch deployment event
    shell: bash
    run: |
      curl -L \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ inputs.GA_TOKEN }}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/one-acre-fund/$%7B%7B  inputs.DISPATCH_REPO }}/actions/workflows/deploy.yml/dispatches \
        -d '{"ref":"${{ inputs.REF }}","inputs":{"run_id":"${{ inputs.RUN_ID }}"}}'
