image:
  registry: docker.io
  repository: mrcea/spark
  tag: v1.2
  digest: ""
master:
  containerPorts:
    https: 8080
  extraEnvVars:
    - name: SPARK_CONF_FILE
      value: /bitnami/conf/spark-defaults.conf
    # - name: SPARK_MASTER_HOST
    #   value: 'localhost'
  extraVolumes:
    - name: spark-defaults
      configMap:
        name: spark-config
  extraVolumeMounts:
    - name: spark-defaults
      mountPath: /opt/bitnami/spark/conf/spark-defaults.conf
      subPath: spark-defaults.conf
      readOnly: false
   
  existingConfigMap: spark-config
worker:
  containerPorts:
    https: 8080
  extraEnvVars:
    - name: SPARK_CONF_FILE
      value: /bitnami/conf/spark-defaults.conf
    # - name: SPARK_MASTER_HOST
    #   value: 'localhost'


  existingConfigMap: spark-config
  resourcesPreset: small

  extraVolumes:
    - name: spark-defaults
      configMap:
        name: spark-config
  extraVolumeMounts:
    - name: spark-defaults
      mountPath: /opt/bitnami/spark/conf/spark-defaults.conf
      subPath: spark-defaults.conf
      readOnly: false

security:
  # passwordsSecretName: spark-secrets

  ssl:
    enabled: true
    autoGenerated: true
    needClientAuth: true
  rpc:
    authenticationEnabled: true
    encryptionEnabled: true
    storageEncrytionEnabled: true
