replicaCount: 1

# service:
#   type: NodePort

# Don't run as root
runAsUser: 1000
bootstrapScript: ""

# supersetNode:
# forceReload: true
# command:
#   - /bin/sh
#   - -c
#   - . {{ .Values.configMountPath }}/superset_bootstrap.sh; /usr/bin/docker-entrypoint.sh

image:
  repository: oaftech.azurecr.io/oneacrefund/superset
  tag: "1.5.1-_3aaeb37c04041f26226771bbae2e96d3655cc3e5"
  # pullPolicy: Always

extraEnv:
  AUTH_DOMAIN: oneacrefund.org
  SMTP_HOST: smtp.gmail.com
  SMTP_USER: yann.jouanique@oneacrefund.org
  SMTP_PORT: "587"
  SMTP_MAIL_FROM: yann.jouanique@oneacrefund.org
  EMAIL_NOTIFICATIONS: "True"
  DEFAULT_ROLE: "Admin"

# extraSecretEnv:
#   MAPBOX_API_KEY: xxxx
#   GOOGLE_KEY: xxxx
#   GOOGLE_SECRET: xxxx
#   SLACK_API_TOKEN: xxxx
#   SMTP_PASSWORD: xxxx

# extraSecrets:
#   datasources-init.yaml: |
#     databases:
#       - database_name: Elastic Hetzner
#         sqlalchemy_uri: elasticsearch+https://oaf_user:@elk.operations.oneacrefund.org:9200/
#         tables: []
#       - database_name: GSheet
#         sqlalchemy_uri: gsheets://
#         tables: []
#       - database_name: Roster_DW
#         sqlalchemy_uri: mssql+pymssql://fredrick.mandela:XXXXXXXXXX@mtama.oneacrefund.org:6543/RosterDatawarehouse
#         tables: []
#       - allow_csv_upload: true
#         database_name: Postgres
#         sqlalchemy_uri: postgresql+psycopg2://superset:XXXXXXXXXX@superset-postgresql:5432/superset
#         tables: []
#       - database_name: Elastic-Azure
#         sqlalchemy_uri: elasticsearch+https://oaf_user:XXXX@api.oneacrefund.org:443/api/elasticsearch/
#         tables: []
#       - database_name: ROSTER
#         sqlalchemy_uri: mssql+pymssql://BOSUser001:XXXXXXXXXX@businessintell.oneacrefund.org:6543/RosterReporting
#         tables: []

# supersetWorker:
#   command:
#     - /bin/sh
#     - -c
#     - . {{ .Values.configMountPath }}/superset_bootstrap.sh; celery --app=superset.tasks.celery_app:app worker

supersetCeleryBeat:
  # this is only required if you intend to use reports and alerts (?)
  enabled: true
# Set storage class for dependent charts
# postgresql.persistence.storageClass: hcloud-volumes
# redis.master.persistence.storageClass: hcloud-volumes
# postgres:
#   master:
#     tolerations:
#       - key: "kubernetes.io/hostname"
#         operator: "Equal"
#         value: "qacluster05node03"
#         effect: "NoSchedule"
# extraConfigs:
#   google-sheet-key.json: |
#     {
#     }

# supersetNode:
#   command:
#     - "/bin/sh"
#     - "-c"
#     - ". {{ .Values.configMountPath }}/superset_bootstrap.sh; /usr/bin/docker-entrypoint.sh"
