apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbt-snowflake-target
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbt-mssql-target
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi