apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
type: Opaque
stringData:
  KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
  KAFKA_CONNECT_SECRET: ${KAFKA_CONNECT_SECRET}
  KAFKA_BRIDGE_SECRET: ${KAFKA_BRIDGE_SECRET}
  