---
replicaCount: 3
heapOpts: "-Xms512M -Xmx512M"
resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi

externalAccess:
  enabled: true
  autoDiscovery:
    enabled: true
  service:
    type: NodePort
  # controller:
    # service:
      # type: NodePort
  # broker:
    # service:
      # type: NodePort

serviceAccount:
  create: true

rbac:
  create: true

# sasl:
  # enabledMechanisms: SCRAM-SHA-256,PLAIN
  # client:
    # users:
      # - kafka_connect
    # passwords:
      # - $(KAFKA_CONNECT_PASSWORD)

kraft:
  enabled: false

zookeeper:
  enabled: true

kafka:
  fullname: "kafka"

controller:
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 2Gi

# listeners:
  # client:
    # protocol: PLAINTEXT

extraDeploy:
  - |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: {{ include "common.names.fullname" . }}-connect
      labels: {{- include "common.labels.standard" . | nindent 4 }}
        app.kubernetes.io/component: connector
    spec:
      replicas: 1
      selector:
        matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
          app.kubernetes.io/component: connector
      template:
        metadata:
          labels: {{- include "common.labels.standard" . | nindent 8 }}
            app.kubernetes.io/component: connector
        spec:
          containers:
            - name: connect
              image: kwalter94/kafka-connect-rabbitmq:v0.0.5
              imagePullPolicy: IfNotPresent
              ports:
                - name: connector
                  containerPort: 8083
              volumeMounts:
                - name: configuration
                  mountPath: /etc/kafka/
          volumes:
            - name: configuration
              configMap:
                name: {{ include "common.names.fullname" . }}-connect
  - |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: {{ include "common.names.fullname" . }}-connect
      labels: {{- include "common.labels.standard" . | nindent 4 }}
        app.kubernetes.io/component: connector
    data:
      connect-standalone.properties: |-
        bootstrap.servers = {{ include "common.names.fullname" . }}.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}:9092
        key.converter = org.apache.kafka.connect.storage.StringConverter
        key.converter.nullable = true
        value.converter = org.apache.kafka.connect.json.JsonConverter
        value.converter.nullable = true
        group.id = oaf-bi
        offset.storage.topic = offsets
        config.storage.topic = config
        status.storage.topic = status
        plugin.path = /usr/share/java,/opt/bitnami/kafka/plugins
        rest.advertised.host.name = localhost
        offset.storage.file.filename = /opt/bitnami/kafka/kafka-connect.offsets
        config.storage.replication.factor = 3
        offset.storage.replication.factor = 3
        status.storage.replication.factor = 3
        # security.protocol = SASL_PLAINTEXT
        # sasl.mechanism = PLAIN
        # sasl.jaas.config = org.apache.kafka.common.security.plain.PlainLoginModule \
            # required \
            # username="kafka_connect" \
            # password="$(KAFKA_CONNECT_PASSWORD)";
      
  - |
    apiVersion: v1
    kind: Service
    metadata:
      name: {{ include "common.names.fullname" . }}-connect
      labels: {{- include "common.labels.standard" . | nindent 4 }}
        app.kubernetes.io/component: connector
    spec:
      ports:
        - protocol: TCP
          port: 8083
          targetPort: connector
      selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
        app.kubernetes.io/component: connector
  - |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: {{ include "common.names.fullname" . }}-kouncil
      labels: {{- include "common.labels.standard" . | nindent 4 }}
        app.kubernetes.io/component: kouncil
    spec:
      replicas: 1
      selector:
        matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
          app.kubernetes.io/component: kouncil
      template:
        metadata:
          labels: {{- include "common.labels.standard" . | nindent 8 }}
            app.kubernetes.io/component: kouncil
        spec:
          containers:
            - name: connect
              image: consdata/kouncil:latest
              imagePullPolicy: IfNotPresent
              ports:
                - name: kouncil
                  containerPort: 8080
              env:
                - name: bootstrapServers
                  value: kafka.bi.svc.cluster.local:9092
                - name: kouncil.auth.active-provider
                  value: inmemory
