# APPLY_FIXES: none
APPLY_FIXES: all
DEFAULT_BRANCH: develop

ENABLE_LINTERS:
  - DOCKERFILE_HADOLINT
  - YAML_PRETTIER
  - MARKDOWN_MARKDOWNLINT
  - PYTHON_PYLINT
  - PYTHON_BLACK

SHOW_ELAPSED_TIME: true
PRINT_ALPACA: false
