apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flink-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flink-artifacts
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi