apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker2
metadata:
  name: my-cluster-mirror-maker-2
spec:
  version: 3.7.1
  replicas: 1
  connectCluster: "my-cluster-b" # Must be the target custer
  clusters:
    - alias: "my-cluster-a" # Source cluster
      bootstrapServers: my-cluster-a-kafka-bootstrap:9093
      authentication:
        type: oauth
        clientId: kafka-connect
        tokenEndpointUri: https://keycloak/realms/kafka-authz/protocol/openid-connect/token
        tlsTrustedCertificates:
          - secretName: keycloak-crt
            certificate: ca.crt
        clientSecret:
          key: KAFKA_CONNECT_SECRET
          secretName: keycloak-secrets
      tls:
        trustedCertificates:
          - secretName: my-cluster-a-cluster-ca-cert
            pattern: "ca.crt"
    - alias: "my-cluster-b" # Target cluster
      bootstrapServers: my-cluster-b-kafka-bootstrap:9093
      authentication:
        type: oauth
        clientId: kafka-connect
        tokenEndpointUri: https://keycloak/realms/kafka-authz/protocol/openid-connect/token
        tlsTrustedCertificates:
          - secretName: keycloak-crt
            certificate: ca.crt
        clientSecret:
          key: KAFKA_CONNECT_SECRET
          secretName: keycloak-secrets
      tls:
        trustedCertificates:
          - secretName: my-cluster-b-cluster-ca-cert
            pattern: "ca.crt"
      config:
        # -1 means it will use the default replication factor configured in broker
        config.storage.replication.factor: -1
        offset.storage.replication.factor: -1
        status.storage.replication.factor: -1
  mirrors:
    - sourceCluster: "my-cluster-a"
      targetCluster: "my-cluster-b"
      sourceConnector:
        tasksMax: 1
        config:
    # -1 means it will use the default replication factor configured in broker
          replication.factor: -1
          offset-syncs.topic.replication.factor: -1
          sync.topic.acls.enabled: "false"
          refresh.topics.interval.seconds: 600
      checkpointConnector:
        tasksMax: 1
        config:
          checkpoints.topic.replication.factor: -1
          sync.group.offsets.enabled: "false"
          refresh.groups.interval.seconds: 600
      topicsPattern: ".*"
      groupsPattern: ".*"
  # metricsConfig:
  #   type: jmxPrometheusExporter
  #   valueFrom:
  #     configMapKeyRef:
  #       name: mirror-maker-2-metrics
  #       key: connect-metrics-config.yml
