apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaBridge
metadata:
  name: my-bridge
spec:
  replicas: 3
  bootstrapServers: my-cluster-a-kafka-bootstrap:9093
  tls:
    trustedCertificates:
      - secretName: my-cluster-a-cluster-cert
        pattern: "*.crt"
      - secretName: my-cluster-a-cluster-cert
        certificate: ca2.crt
  authentication:
    type: tls
    certificateAndKey:
      secretName: my-secrets
      certificate: public.crt
      key: private.key
  http:
    port: 8080
    cors:
      allowedOrigins: "*"
      allowedMethods: "GET,POST,PUT,DELETE,OPTIONS,PATCH"
  enableMetrics: true
  consumer:
    config:
      auto.offset.reset: earliest
  producer:
    config:
      delivery.timeout.ms: 300000
  resources:
    requests:
      cpu: "1"
      memory: 2Gi
    limits:
      cpu: "2"
      memory: 2Gi
  logging:
    type: inline
    loggers:
      logger.bridge.level: INFO
      # enabling DEBUG just for send operation
      logger.send.name: "http.openapi.operation.send"
      logger.send.level: DEBUG

  readinessProbe:
    initialDelaySeconds: 15
    timeoutSeconds: 5
  livenessProbe:
    initialDelaySeconds: 15
    timeoutSeconds: 5
