apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name:  my-cluster-debezium-postgres-connector  # (1)
  labels:
    strimzi.io/cluster: my-connect-cluster-pool-b # (2)
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  tasksMax: 1
  config:
    database.hostname: database-postgresql
    database.port: 5432
    database.user: replicator
    database.password: replica123&
    database.dbname: development
    topic.prefix: users
    plugin.name: pgoutput
    # publication.autocreate.mode: filtered
    # schema.include.list: '*'
    # table.include.list: '*'

---

apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: camel-rabbitmq-connector  # (1)
  labels:
    strimzi.io/cluster: my-connect-cluster-pool-b # (2)
spec:
  # yamllint disable-line rule:line-length
  class: org.apache.camel.kafkaconnector.springrabbitmqsource.CamelSpringrabbitmqsourceSourceConnector
  tasksMax: 1
  config:
    camel.kamelet.spring-rabbitmq-source.host: eventing-rabbitmq
    camel.kamelet.spring-rabbitmq-source.port: 5672
    camel.kamelet.spring-rabbitmq-source.routingKey: '#.kafka.*'
    camel.kamelet.spring-rabbitmq-source.username: rabbitmqAdmin
    camel.kamelet.spring-rabbitmq-source.password: RabAdmin123
    camel.kamelet.spring-rabbitmq-source.exchangeName: 'testing-ex'
    camel.kamelet.spring-rabbitmq-source.queues: kafka-queue
    camel.kamelet.spring-rabbitmq-source.autoDeclare: false
    topics: users.rabbitmq
