apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaBridge
metadata:
  name: my-cluster-bridge
spec:
  replicas: 1
  bootstrapServers: my-cluster-a-kafka-bootstrap:9093
  tls:
    trustedCertificates:
      - secretName: my-cluster-a-cluster-ca-cert
        certificate: ca.crt
  authentication:
    type: oauth
    clientId: kafka-bridge
    tokenEndpointUri: https://keycloak/realms/kafka-authz/protocol/openid-connect/token
    tlsTrustedCertificates:
      - secretName: keycloak-crt
        certificate: ca.crt
    clientSecret:
      key: KAFKA_BRIDGE_SECRET
      secretName: keycloak-secrets
    enableMetrics: false
  http:
    port: 9098
    cors:
      allowedOrigins:
        - "http://*"
        - "https://*"
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
        - PATCH
  enableMetrics: false
  consumer:
    config:
      auto.offset.reset: earliest
      group.id: api
  producer:
    config:
      delivery.timeout.ms: 300000
  resources:
    requests:
      cpu: "1"
      memory: 2Gi
    limits:
      # cpu: "2"
      memory: 2Gi
  logging:
    type: inline
    loggers:
      logger.bridge.level: INFO
      # enabling DEBUG just for send operation
      logger.send.name: "http.openapi.operation.send"
      logger.send.level: DEBUG

  # readinessProbe:
  #   initialDelaySeconds: 15
  #   timeoutSeconds: 5
  # livenessProbe:
  #   initialDelaySeconds: 15
  #   timeoutSeconds: 5
  # bridgeContainer: # (15)
  #   env:
  #     - name: OTEL_SERVICE_NAME
  #       value: my-otel-service
  #     - name: OTEL_EXPORTER_OTLP_ENDPOINT
  #       value: "http://otlp-host:4317"
  # tracing:
  #     type: opentelemetry # (16)
