apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: debezium-postgres-connector  # (1)
  labels:
    strimzi.io/cluster: my-connect-cluster-pool-b # (2)
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  tasksMax: 1
  config:
    database.hostname: database-postgresql
    database.port: 5432
    database.user: replicaUser
    database.password: ${REPLICATIONPASSWORD}
    database.dbname: users
    topic.prefix: users
    plugin.name: pgoutput
    publication.autocreate.mode: filtered
    schema.include.list: ''
    table.include.list: ''

---

apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: camel-rabbitmq-connector  # (1)
  labels:
    strimzi.io/cluster: my-connect-cluster-pool-b # (2)
spec:
  # yamllint disable-line rule:line-length
  class: org.apache.camel.kafkaconnector.springrabbitmqsource.CamelSpringrabbitmqsourceSourceConnector
  tasksMax: 1
  config:
    camel.kamelet.spring-rabbitmq-source.host:
    camel.kamelet.spring-rabbitmq-source.port:
    camel.kamelet.spring-rabbitmq-source.routingKey: '#.kafka.*'
    camel.kamelet.spring-rabbitmq-source.username:
    camel.kamelet.spring-rabbitmq-source.password:
    camel.kamelet.spring-rabbitmq-source.exchangeName: 'testing-ex'
