yamlApplicationConfig:
  kafka:
    clusters:
      - name: local
        bootstrapServers: my-cluster-a-kafka-bootstrap:9093
        properties:
          security:
            protocol: 'SSL'
        ssl:
          truststoreLocation:
          truststorePassword:

        schemaRegistry: ''

        schemaRegistrySSL:
          keystoreLocation:
          keystorePassword:

        metrics:
          type: PROMETHEUS
          port: 9404
          keystoreLocation:
          keystorePassword:

        kafkaConnect:
          - name:
            address:
            keystoreLocation:
            keystorePassword:

  auth:
    type: OAUTH2
    oauth2:
      client:
        keycloak:
          clientId: xxx
          clientSecret: yyy
          scope: openid
          issuer-uri: https://<keycloak_instance>/auth/realms/<realm>
          user-name-attribute: preferred_username
          client-name: keycloak
          provider: keycloak
          custom-params:
            type: oauth
  rbac:
    roles:
      - name: "dataeng"
        clusters:
          - local
        subjects:
          - provider: oauth
            type: user
            value: "memelord.lol"
          - provider: oauth
            type: role
            value: "kek@memelord.lol"
        permissions:
          - resource: applicationconfig
            # value not applicable for applicationconfig
            actions: ["view", "edit"] # can be with or without quotes
          - resource: clusterconfig
            # value not applicable for clusterconfig
            actions: ["view", "edit"]
          - resource: topic
            value: "ololo.*"
            actions: # can be a multiline list
              - VIEW # can be upper or lowercase
              - CREATE
              - EDIT
              - DELETE
              - MESSAGES_READ
              - MESSAGES_PRODUCE
              - MESSAGES_DELETE

          - resource: consumer
            value: "\_confluent-ksql.*"
            actions: [VIEW, DELETE, RESET_OFFSETS]

          - resource: schema
            value: "blah.*"
            actions: [VIEW, CREATE, DELETE, EDIT, MODIFY_GLOBAL_COMPATIBILITY]

          - resource: connect
            value: "local"
            actions: [view, edit, create, restart]
          # connectors selector not implemented yet, use connects
          #      selector:
          #        connector:
          #          name: ".*"
          #          class: 'com.provectus.connectorName'

          - resource: acl
            # value not applicable for acl
            actions: [view, edit]

  management:
    health:
      ldap:
        enabled: false
