apiVersion: v1
kind: Secret
metadata:
  name: kafka-user-secrets
type: Opaque
stringData:
  USER_PASSWORD: ${SCRAM_PASSWORD}


---

apiVersion: v1
kind: Secret
metadata:
  name: docker-secret
type: Opaque
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "https://index.docker.io/v1/": {
          "auth": ${MY_AUTH}
        }
      }
    }
