apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
stringData:
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_ADMIN_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
  REPLICATION_PASSWORD: ${REPLICATION_PASSWORD}
  KEYCLOAK_USER_DB_PASSWORD: ${KEYCLOAK_USER_DB_PASSWORD}
  AIRBYTE_USER_DB_PASSWORD: ${AIRBYTE_USER_DB_PASSWORD}
  AIRFLOW_USER_DB_PASSWORD: ${AIRFLOW_USER_DB_PASSWORD}
  NOTEBOOK_USER_DB_PASSWORD: ${NOTEBOOK_USER_DB_PASSWORD}

  initdb-script1.sql: |
    \c postgres postgres
    CREATE USER ${KEYCLOAK_USER} WITH encrypted PASSWORD '${KEYCLOAK_USER_DB_PASSWORD}' ;
    CREATE DATABASE ${KEYCLOAK_DB} with OWNER ${KEYCLOAK_USER};
    GRANT ALL PRIVILEGES ON DATABASE ${KEYCLOAK_DB} TO ${KEYCLOAK_USER} ;
    GRANT ALL ON SCHEMA public TO  ${KEYCLOAK_USER};

  initdb-script2.sql: |
    \c postgres postgres
    CREATE USER ${AIRBYTE_USER} WITH encrypted PASSWORD '${AIRBYTE_USER_DB_PASSWORD}' ;
    CREATE DATABASE ${AIRBYTE_DB} with OWNER ${AIRBYTE_USER};
    GRANT ALL PRIVILEGES ON DATABASE ${AIRBYTE_DB} TO ${AIRBYTE_USER};
    GRANT ALL ON SCHEMA public TO ${AIRBYTE_USER};

  initdb-script3.sql: |
    \c postgres postgres
    CREATE USER ${AIRFLOW_USER} WITH encrypted PASSWORD '${AIRFLOW_USER_DB_PASSWORD}';
    CREATE DATABASE ${AIRFLOW_DB} with OWNER ${AIRFLOW_USER};
    GRANT ALL PRIVILEGES ON DATABASE  ${AIRFLOW_DB} TO ${AIRFLOW_USER};
    GRANT ALL ON  SCHEMA public TO ${AIRFLOW_USER} ;

  initdb-script4.sql: |
    \c postgres postgres
    CREATE ROLE ${REPLICA_USER} WITH encrypted PASSWORD '${REPLICATION_PASSWORD}' REPLICATION SUPERUSER;
    ALTER ROLE replicator LOGIN;

  initdb-script5.sql: |
    \c postgres postgres
    CREATE USER ${NOTEBOOK_USER} WITH encrypted PASSWORD '${NOTEBOOK_USER_DB_PASSWORD}' ;
    CREATE DATABASE ${NOTEBOOK_DB} with OWNER ${NOTEBOOK_USER};
    GRANT ALL PRIVILEGES ON DATABASE ${NOTEBOOK_DB} TO ${NOTEBOOK_USER} ;
    GRANT ALL ON SCHEMA public TO  ${NOTEBOOK_USER};
