name: airflow 
run-name: airflow-${{ github.ref_name }}-${{ github.run_number }}
on:
  push:
    branches:
      - airflow
      - main
      - develop
      - release

      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Get Image Tag
      id: get_image_tag
      run: |
        IMAGE_TAG="${SUPERSET_VERSION}_$(date +'%Y%m%d').${{ github.run_number }}"
        [[ "$GITHUB_REF" == "refs/heads/master" ]] && IMAGE_TAG="$IMAGE_TAG,latest"
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Azure registry
      uses: docker/login-action@v3.0.0
      with:
        registry: oaftech.azurecr.io
        username: ${{ vars.ACR_PULL_USERNAME }}
        password: ${{ secrets.ACR_PULL_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: ./airflow/custom_image
        push: true
        tags: oaftech.azurecr.io/airflow:1.0.4
    
    - name: Copy files
      run: |
        mkdir -p ${{ github.workspace }}/releases/airflow
        cp -r airflow/releases/* ${{ github.workspace }}/releases/airflow

    - name: Upload releases artifact
      uses: actions/upload-artifact@v3
      with:
        name: releases
        path: ${{ github.workspace }}/releases/airflow

    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        # artifactErrorsFailBuild: true
        artifacts: ${{ github.workspace }}/releases/airflow
        body: |
         - Deployment process moved from azure pipelines to github actions
         - Removed Azure Pipelines.yml file
         - Updated Actions Files
        tag:  ${{ steps.get_image_tag.outputs.IMAGE_TAG }}
        name:  Airflow_${{ steps.get_image_tag.outputs.IMAGE_TAG }}
        generateReleaseNotes: true
        token: ${{ secrets.GITHUB_TOKEN }}

